### ISSUE TITLE
Make the Terra whitelist less restrictive

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#1056]
Adding individual users to the Terra whitelist is cumbersome and impedes seamless on-boarding of new users. We would like to open up the whitelist to:
* Every user with a @broadinstitute.org user ID
* Every user with a @verily.com user ID
* Every user with a @channing.harvard.edu user ID
* Users added to the existing whitelist

**Comment by mbookman** [comment]
Related to this - it would be nice if the message users see regarding the whitelist was a bit more informative. Currently I see only:

```
Terra is under development. If you are interested in contributing feedback as part of our user panel, please email saturn-dev@broadinstitute.org.
Sign out
```

When someone cannot access Terra, it would be very helpful if we displayed the current signed-in email address that we are testing. Otherwise step 1 when helping researchers is to make sure that they are accessing Terra with the right email address.

Worst case, it would be nice if the code in auth.js that sets the "unlisted" registration status dumped information to the developer console with the email address and md5 being checked against the whitelist.

**Comment by elizzhao** [comment]
First step: ensure people with the specified three domains can access + everyone currently on the whitelist
Second step: FC registered users and other select users we add.

**Comment by elizzhao** [comment]
First step finished, second step is being tracked by #1100
