### ISSUE TITLE
FR: Workspace description revisions

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/saturn-ui#1130]
It would be great if there were change tracking/revisions for workspace descriptions.

Right now we are doing this manually by using a GoogleDoc as the source of truth for the markdown and periodically copying over its contents on top of the existing workspace description.

I've seen similar systems use [a wiki](https://en.wikipedia.org/wiki/List_of_wiki_software) for the underlying implementation to provide change tracking/revisions along with potential for hierarchical content when the main page gets too long.

**Comment by schaluva** [comment]
@deflaux 
Hi there Nicole, thanks for posting some great Feature Request ideas! Just wanted to jump in and let you know that going forward, we will be re-directing and asking users to make Feature Request posts/suggestions to the Terra Support Feature Request Page linked [here](https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500452-Feature-Requests). This will allow users to check on current requests and up-vote ones that they find will be most useful which will lend a hand in prioritizing next steps in terms of features. Since this process has been agreed upon by PMs, posting there will ensure greatest visibility to all the members of the teams working on bringing about new features. Thanks again!

**Comment by bradtaylor** [comment]
This is a great idea, and I definitely see the need. However, changing how these descriptions are stored is likely to be a heavy lift on the backend. We are pretty constrained there with our need to focus on scaling our infrastructure. I don't foresee this getting worked on in the near term. It should be added to our general workspaces requirements.

If it's acceptable to you @deflaux, I'm going to close this issue. Otherwise I suspect it would just hang near the bottom of our backlog
