### ISSUE TITLE
FR: Allow owners to change the authorization domain on an existing or cloned workspace

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/saturn-ui#1170]
I created a workspace with a very narrow authorization domain. I later realized that it was unnecessarily narrow. I wanted the group that I share with to be fairly narrow, but the full domain of people I could share with didn't need to be so restrictive.

I now have a few imperfect options:

1- Add everyone that I now want to share with to my authorization domain.
2- Create a new workspace with the right authorization domain and clone my notebooks manually.

I don't even have the option of cloning the workspace and *changing* the authorization domain. When cloning a workspace I am forced to bring along the original authorization domain. I realize the intent here to prevent accidental sharing, but the current system makes it very hard for a user to correct a simple mistake like this.

I feel like we should give users the option of changing the authorization domain with lots of warnings and explanations about their actions.

**Comment by schaluva** [comment]
@mbookman 
Thank you for the feedback- small accidental mistakes setting Auth Domain are difficult to correct! Going forward, we will be re-directing and asking users to make Feature Request posts/suggestions to the Terra Support Feature Request Page linked [here](https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500452-Feature-Requests). This will allow users to check on current requests and up-vote ones that they find will be most useful which will lend a hand in prioritizing next steps in terms of features. Since this process has been agreed upon by PMs, posting there will ensure greatest visibility to all the members of the teams working on bringing about new features. Thanks Matt!

**Comment by bradtaylor** [comment]
Unfortunately this behavior is something I don't think we can change without significant thought. The auth domain setup can be restrictive, but there were important use cases for having it work that way. And we may have certain projects or contracts where the current behavior is assumed. So changing that would involve a lot of review.

I do think we can do more to warn people up front about the restrictiveness of the current behavior, and let them know they will not be able to change it, prior to setting one up.

This is really a team wide feature discussion, since it touches so many parts of the system. That discussion is probably best had on the feature requests page @schaluva linked. I'm going to close this issue as I don't think there's a lot of actions we're set up to take now.
