### ISSUE TITLE
Seeing a cluster creation error

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#214]
See screenshot below. I have an auto-generated cluster that is failing to create. I think cluster creation has been failing for me consistently in this project going back to the introduction of autocreation, but I cannot confirm that. The particular error is a 503, which seems strange. I have noticed this error popup repeatedly over several logins over the course of a few hours today.

Requirements:
- User knows how to recover from this error. 

![Screen Shot 2018-05-31 at 10.35.20 PM.png](https://images.zenhubusercontent.com/5a6a39f34b5806bc2bc45274/8c4413d3-44f8-4546-94d9-45a594c787aa)

**Comment by rtitle** [comment]
Hello, I checked Leo logs for this cluster error and found this:
```
[ERROR] [02:34:23.898] [leonardo-akka.actor.default-dispatcher-20] o.b.d.w.l.d.g.HttpGoogleDataprocDAO - Call to Google API failed for nci-tiffanym-bi-org / saturn-9ce5b142-b205-4a85-9673-db2b7d790ba0. Status: 403. Message: Cloud Dataproc API has not been used in project 972563046109 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=972563046109 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
 "code" : 403,
 "errors" : [ {
   "domain" : "usageLimits",
   "message" : "Cloud Dataproc API has not been used in project 972563046109 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=972563046109 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
   "reason" : "accessNotConfigured",
   "extendedHelp" : "https://console.developers.google.com"
 } ],
 "message" : "Cloud Dataproc API has not been used in project 972563046109 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=972563046109 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
 "status" : "PERMISSION_DENIED"
}
```
Looks like Dataproc is disabled in this project. It's odd because it is usually enabled in new FC billing projects. Was this project created in the normal way?

Leo should probably handle this error more gracefully than returning a 503 (I think what is happening is Leo is retrying after this error and eventually timing out the request).

**Comment by dmohs** [comment]
Spoke to Rob over Slack about this. This is an interesting case because creating a billing project should cause the necessary APIs to be enabled. He will file a Leo bug to improve the error message (503 Service Unavailable isn't quite clear). I will close this bug for now and we'll see what happens if and when we encounter this case again.

**Comment by rtitle** [comment]
Leo ticket: https://github.com/DataBiosphere/leonardo/issues/406
