### ISSUE TITLE
Change data explorer data import to support Rawls json

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#445]
We currently allow the import of data from Data Explorers via the BagIt data interchange format. Explorers can create a signed URL to retrieve a bagit and send that to Saturn as a URL parameter at our data import page. See:
https://bvdp-saturn-prod.appspot.com/#import-data?url=https%3A%2F%2Fgithub.com%2Fbroadinstitute%2Ffirecloud-orchestration%2Fblob%2Fdevelop%2Fsrc%2Ftest%2Fresources%2Ftestfiles%2Fbagit%2Ftestbag.zip%3Fraw%3Dtrue
Under the hood, our Saturn passes the signed URL to the following Orchestration endpoint. This endpoint requires that data conform to the participant/sample/pairs hierarchy:
https://api.firecloud.org/#!/Entities/importBagit

However, for the BVDP Data Explorer we do not necessarily want to use the bagit format. Nor do we want to limit ourselves to the FireCloud data model. Instead, this explorer can create the JSON structure that Rawls expects when loading custom entity types via the following API:
https://rawls.dsde-prod.broadinstitute.org/#!/entities/create_entity

The data explorer may wish to send multiple entity tables to Saturn as part of a single import statement. The data explorer will therefore send us a signed URL to a zip file containing one or more json files. Our UI should support this and use the JSON to post new table(s) to Rawls. 

We can include a URL flag indicating if the format is bagit or json when accepting the zip file URL. We could reformat the json and use the batchUpsert API to put in all the entities in one call:
https://rawls.dsde-prod.broadinstitute.org/#!/entities/batch_upsert_entities
child of #353

**Comment by melissachang** [comment]
I spent some time seeing if we can directly POST the JSON, rather than deal with GCS files/signed urls.

Using this [StackOverflow question](https://stackoverflow.com/questions/133925/javascript-post-request-like-a-form-submit) as an example, I was able to:
- On button click, send a POST request
- Redirect to the html response of the POST request

I'm happy to put an example on github somewhere if you want.

@dmohs , what do you think of this simpler idea? So Saturn UI would:
- GET import-data - This would not change
- POST import-data - RAWLS JSON will be passed via POST body

@alahwa @ahaessly

**Comment by melissachang** [comment]
N/m, @panentheos pointed out that only server can access POST body, not client. We'll do what Brad said.

**Comment by panentheos** [comment]
To import data in the new json format, link to the following:

https://bvdp-saturn-prod.appspot.com/#import-data?format=entitiesJson&url=XXX

Where XXX is the URL where the file can be downloaded, properly url-encoded.
