### ISSUE TITLE
Click outside a modal to close the modal.

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#493]
User requested:
"Would be nice if clicking outside of the File Details overlay (and any other similar overlay) would close it. It’s hard to click on that little x!"

**Comment by dmohs** [comment]
Whether or not we want clicking outside to close the modal, we certainly should adding padding around the X to make the clickable area larger.

**Comment by bradtaylor** [comment]
I think @zarsky-broad has opinions regarding why click-outside-to-close may not be desirable here. Isaac, care to comment?

**Comment by zarsky-broad** [comment]
It just needs to be on a per-modal basis. Something like the file details is really just a lightbox, so that's fine. For modals where we want an explicit user response, we may want to require actually clicking a button, so that something that really needs interaction can't be closed by mistake. I'm happy to leave this up to @martygardner

**Comment by martygardner** [comment]
+1 to Isaac's argument. 

Lou and I discussed this and realized we need to be more consistent. For example, the current VM settings treatment [Invision](https://invis.io/8AMZOAA6BNM#/290093597_VM_Panel_Open_Spark) is a weighty dialog but has a secondary way to exit with the drop-down-style arrow. This shouldn't be. We plan to change this to a button/icon launching standard modal, and will be on the lookout for other strays as well.
 
![image](https://user-images.githubusercontent.com/33694045/43964731-786fa88a-9c8b-11e8-9fec-75ed58e34e27.png)
