### ISSUE TITLE
Loading clusters error is inconsistently formatted

### ISSUE THREAD

**Issue by katevoss** [DataBiosphere/saturn-ui#549]
While testing notebook uploads, I came across a `Error loading clusters`. When I clicked `Details`, it displays a large box that is formatted differently than the rest of the error details:

<img width="1348" alt="screen shot 2018-08-22 at 10 11 00 am" src="https://user-images.githubusercontent.com/2395211/44468641-ae9d9900-a5f3-11e8-81b5-4dda524e8989.png">

**Comment by katevoss** [comment]
Additional information for investigation:
I didn't interact with the Notebooks for about 2 hours. Then I tried to upload an ipynb, and saw an error in the console. I refreshed and got the following errors:
<img width="1265" alt="screen shot 2018-08-22 at 3 30 24 pm" src="https://user-images.githubusercontent.com/2395211/44485996-621c8280-a620-11e8-80d6-e0c98409ce65.png">

**Comment by MattPutnam** [comment]
Google auth errors come back as HTML (instead of the JSON that we get from our services), so the error viewer is designed to handle both. In the HTML case, we simply display the content in an iframe. I don't know if we can reliably apply formatting to that, but maybe we could add a note saying this is the raw response.

@katevoss That CORS error usually means that the backend service is down, which is usually because it's redeploying.

**Comment by bradtaylor** [comment]
The only solutions appear to be hacky. We are deciding to live with this as-is for now.
