### ISSUE TITLE
Copy-to-clipboard feature for emails in the Groups page

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#553]
Feature request. A user may want to copy over the email for a group (such as in scenarios where there are many emails that are similar to each other). So a "copy to clipboard" button may be helpful to place next to the email. 

Currently, a user cannot select the email of group with Admin access.

![Screen Shot 2018-08-22 at 9.50.11 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/2f35e663-4db4-48b1-b20b-733aed71119c)

**Comment by dmohs** [comment]
Related: The clickable area for the trash icon is too small. Miss by a few pixels and I unexpectedly land on the details page. I suggest the clickable area for the details page extends to 1-2rem before the email address starts.

**Comment by zarsky-broad** [comment]
As an alternative to a copy to clipboard button, I vote for having only the name be clickable, so that the email can be highlighted.

**Comment by bradtaylor** [comment]
I agree with Isaac. The group email address is not styled as a link. I expect that trying to click on it would highlight it, so that I can copy it, like any other text. I can do that on groups I only have member access to. The name is already styled in blue, like a link. Let's make that and the trash icon the only clickable elements, instead of the whole row. We can pad out the clickable area of the trash icon by 1-2rem as well (as I think we've done other places?
