### ISSUE TITLE
Saturn logo on Groups pages links back to Groups -- how useful is this?

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#557]
This is regarding the saturn logo:
![Screen Shot 2018-08-22 at 9.57.59 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/4e416f8e-8bd2-4a07-b7a8-86d3c5d1eca8)

Everywhere else on Saturn, the logo will redirect the user to the workspaces page. When the user is on the groups page, it changes to the Groups page. I can see how this could be useful for a user who needs to look at multiple groups and doesn't know how to use the browser's back navigation. However, my feeling (based on my own needs) is that a user might want to go back to the workspaces page more often than back to the groups page. We might want to get some user input on this to make sure we're doing the right thing.

**Comment by MattPutnam** [comment]
I made it do that because there was no way (besides the back button, which people don't know to use) to get back to the groups list after clicking into one. I think we're also trying to move away from the workspaces list being the default landing page.

In general, we've neglected that bit of navigation and should take a closer look at what we want to do there.

**Comment by bradtaylor** [comment]
There will ultimately be a Saturn home page that allows direct access to data browse, tool browse, and workspace browse. These Saturn links may be directed there, or remain self referential. There's going to be an explicit effort around top level app navigation.

We do foresee users who will only use the data library for finding/downloading data (that's fine). We foresee users who will only use job manager when it's in place. So basically, Matt is correct on all counts.

We'll get there
