### ISSUE TITLE
Dropdown / display info on Job History page on mouseover

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/saturn-ui#558]
A story of photos:
![Screen Shot 2018-08-22 at 10.10.58 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/e0ccc0e6-c22f-448f-89b3-777f27556659)
![Screen Shot 2018-08-22 at 10.10.54 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/e1f4c5c8-e763-41c5-843c-2e331b8b74fe)
![Screen Shot 2018-08-22 at 10.11.26 AM.png](https://images.zenhubusercontent.com/5b34ecd789c1fc1ffe8ce953/bc41fd34-dcfb-4c49-9087-b89996c97e20)

**Comment by andy7i** [comment]
In words:

it's annoying to have to click on the status arrow in order to get the status breakdown

if a user is putting their mouse over the icon, they probably want to get that info

so we can save them (or at least just me) a step

**Comment by bradtaylor** [comment]
I'm happy for the status details to be a mouseover on the status. I'd like the 'view job details' one to remain tied to clicking the icon. Why? A) it's less frequent. B) I don't want to tie it to mousing over the 'down' icon, because there's clickable stuff in that list. I want to avoid that frustrating experience where a clickable list is triggered by a mouseover, and mousing away even for a moment causes the list to disappear. It makes it really difficult to actually click on an element from the list.

@martygardner What do you think? You've got more experience here so I'd rather defer to you

**Comment by martygardner** [comment]
A few thoughts:

1) Clicking an item in the list should view its details, unless that concept just doesn't apply for the item type. This is consistent behavior across Saturn.

2) Context menus are intended for organizing secondary actions. See images below for how this was originally wireframed for jobs. If the only action is to open the thing, a menu is not necessary. 

![image](https://user-images.githubusercontent.com/33694045/44726722-61fc0700-aaa6-11e8-83ea-4493b5a50ee4.png)
![image](https://user-images.githubusercontent.com/33694045/44726810-91127880-aaa6-11e8-841e-2063360ede18.png)

3) Affordances should work consistently, so we should not have some triangle affordances that expand on hover and some that require a click. I'm inclined to make things with a menu icon and a resulting list of clickable actions require a click, but I agree with the point about the status breakdown feeling like it should be a hover. Maybe the solution is that the status breakdown doesn't use the menu iconography but just appears on hover over the icon.

**Comment by bradtaylor** [comment]
We would like to move the status breakdown to a hover with no triangle icon. 

We will keep the context menu on the workflow as-is.

**Comment by bradtaylor** [comment]
@panentheos has some changes regarding tooltip shape. See him if picking this up.
