### ISSUE TITLE
Bring in MUI components

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/saturn-ui#59]
Using https://material-ui-next.com

**Comment by zarsky-broad** [comment]
I'm punting on this for now. Material-ui needs to do some updating; right now it causes warnings with the current react version, and I managed to get into an endless loop situation where my Chrome tab crashed. It's also a not-insignificant addition to the size of the build.

**Comment by zarsky-broad** [comment]
@dmohs gave verbal ok to close this.

**Comment by melissachang** [comment]
Hey, I was checking to see what Material library you were using, and found this Issue.

material-ui 1.0 was released on May 17, 2018. They've also made a bunch of changes since then (current version is 3.1.2). So the problems you saw earlier may have been fixed. We're using a bunch of material-ui components without problems.

The next time you need a new component, please consider https://material-ui.com/ . (The [blog post](https://medium.com/material-ui/material-ui-v1-is-out-e73ce13463eb) says "Our components now work in isolation. You should be able to use a single Material-UI component in an existing codebase without any side effect. No global CSS override needed, no bundle size bloat.".)

**Comment by zarsky-broad** [comment]
@dmohs @panentheos Thoughts?

**Comment by panentheos** [comment]
We can certainly consider it. I think we should treat it like any other library: if it's a good fit for a problem that we need to solve, then we use it. Otherwise, we don't.
