### ISSUE TITLE
Public workspaces show up on my workspace list page

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/saturn-ui#680]
In Saturn dev, I see the following workspaces which I assume are public:

![image](https://user-images.githubusercontent.com/822298/45790154-54b2e200-bc38-11e8-8677-4841da7080b3.png)

Last week @bradtaylor indicated this was not the expected behavior.

**Comment by calbach** [comment]
(Ignore "adfasdfasd" that one's actually mine)

**Comment by panentheos** [comment]
Confirmed that this is a bug, we will fix this.

**Comment by MattPutnam** [comment]
This is the same problem that we ran into with FC. If a WS gets listed, that's because it's either public, shared with you, or both. But, if it's shared with you as a Reader, then you don't have permission to see the ACL. So if it's public and you're not a writer/owner, you can't tell if you're a reader or not. So we can't reliably filter out public workspaces.
