### ISSUE TITLE
Adjust FireCloud data library to work from Saturn

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#770]
We are going to be linking users to the FireCloud data library to find datasets hosted by Broad as workspaces. Per #768 

Ultimately, we're going to replace this with integrated dataset search in the Saturn library powered by data repository. However, linking to FireCloud will serve to expose this content sufficiently early in our beta phase that we can find new users.

As we are sending users to a different system, we want to:
1) Provide them a way to get back
2) Minimize the disruption

To this end, we intend to modify https://portal.firecloud.org/#library when a user arrives there from Saturn. How will we know a user is arriving from Saturn? @panentheos has recommended adding a query parameter to the URL to capture this state. The URL therefore specifies when we want to display a Saturn-modified view of this page.

How will we modify the page?
The primary function of the page is to search for datasets represented as FireCloud workspaces. The primary result of a search is a list of links to workspaces matching the search criteria. To accomplish aim (1), we want these workspace links to direct to the Saturn version of the workspace. So instead of:
https://portal.firecloud.org/#workspaces/broad-firecloud-tcga/TCGA_LAML_OpenAccess_V1-0_DATA
We want
\<saturn-base-url\>/#workspaces/blahblahblah

To accomplish aim (2), we want to remove the page header, which links to many other parts of FireCloud we don't want the user poking at (like the workspace list, methods repo, profile info, etc). We similarly want to remove the footer (which links to FireCloud TOS, docs, forum, etc).

Ideally, we could replace the header line with a new one containing a link back to \<saturn-base-url\>/#browse-data, but this is optional.

Things we don't care about:
* The visual styling on the FC data library page is widely divergent from the rest of the Saturn app
* The URL is under a different domain than the rest of the application.

Ok, we care about those things. But not enough to fix them at this time unless it's dang easy

**Comment by katevoss** [comment]
@bradtaylor a topic to ponder related to the Data Library: when a user has access to NIH Commons datasets, their Firecloud Profile knows about their NIH Commons access. Right now they go through Firecloud to link to their NIH Commons identity. This is not currently possible in Saturn, but I believe that it will need to be.

We came across this situation when a user is viewing the FC Data Library in the minimalist-Terra view. When the user's credentials are out of date they see the orange notification bar to "Re-Link" with their NIH account. Unfortunately this takes them to the FC profile page, which is undesired since we want to keep users on the Terra-view.
