### ISSUE TITLE
Make table download respect column selections

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/saturn-ui#833]
A user has un-selected columns in the data table UI. When the user downloads a TSV, the TSV should not contain un-selected columns.

**Comment by panentheos** [comment]
The backend does not currently provide a way to download a subset of the entities, so this would need to be added.

Also, keep in mind that checkbox selection can only be done within a single page of items, whereas TSV download covers the whole table, so there's a conceptual mismatch there.

We could do this trivially for copy-to-clipboard though, since that's per-page and done entirely on the client.

**Comment by bradtaylor** [comment]
This is about column selection.
