### ISSUE TITLE
Groups page shows same group twice

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/saturn-ui#867]
baseline-researchers is shown twice. I am an Admin of baseline-researchers.

![groups](https://user-images.githubusercontent.com/10929390/48509182-3961ee80-e805-11e8-93c2-8cccddbba833.png)

**Comment by kleighwe** [comment]
Notes from Refinement:
- When we change a persons role, is it just adding them as the new role and keeping the old one? 
- This ticket should be a lightweight UI Fix, and we'll do another story to prevent the duplication of roles in the first place.

**Comment by breilly2** [comment]
Further thoughts after refinement: In the general case (in sam), roles are not necessarily in a hierarchy. Member doesn't have to be a subset of Admin. I suspect that's why the current implementation allows both roles to be assigned.

I suspect for groups that Member currently _is_ a subset of Admin... and maybe we can count on that always being true. If so, we could encode that in the orchestration group API. However, we shouldn't expect something like that to ever be encoded into the sam API.
