### ISSUE TITLE
Prevent the duplication of roles in Terra

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/saturn-ui#975]

**Comment by katevoss** [comment]
@kleighwe Do you happen to remember any more context about this issue? Is it about the Admin/Member issue, like #1166 ?

**Comment by bradtaylor** [comment]
I believe this was related to the admin/member role duplication on groups. We are resolving this via a different issue as part of our billing epic. It will apply to groups as well. I'm going to mark this as a duplicate and close this issue as the fix will not be tied here.

Kendra, if you feel like this issue is not resolved as of 3/8, please reopen.
